spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: domi-service
          uri: lb:http://DOMI-SERVICE
          predicates:
            - Path=/api/v1/domi/**
        - id: authentification-service
          uri: lb:http://AUTHENTIFICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: refproject-service
          uri: lb:http://REFPROJECT-SERVICE
          predicates:
            - Path=/api/v1/ref/**
        - id: gen-service
          uri: lb:http://GEN-SERVICE
          predicates:
            - Path=/api/v1/gen/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservice
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8222
